name: Subscribe Emails

on:
  workflow_dispatch:
  repository_dispatch:
    types: [subscribe]

jobs:
  subscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append email to file
        run: |
          echo "${{ github.event.client_payload.email }}" >> emails.txt

      - name: Commit emails
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add emails.txt
          git commit -m 'Add new email'
          git push
